# Note: This file is produced automatically, and will be overwritten the next
# time you press "Generate" in System Generator. 
#


namespace eval ::xilinx::dsp::planaheaddriver {
	set BoardFileVersion {1.4}
	set BoardName {zcu111}
	set BoardRevision {Rev}
	set BoardVendor {xilinx.com}
	set Compilation {IP Catalog}
	set CompilationFlow {IP}
	set CreateInterfaceDocument {off}
	set DSPDevice {xczu28dr}
	set DSPFamily {zynquplus}
	set DSPPackage {ffvg1517}
	set DSPSpeed {-2-e}
	set FPGAClockPeriod 1.81818
	set GenerateTestBench 0
	set HDLLanguage {verilog}
	set IPOOCCacheRootPath {/home/jpsmith/.Xilinx/Sysgen/SysgenVivado/lnx64.o/ip}
	set IP_Auto_Infer {1}
	set IP_Categories_Text {gen3}
	set IP_Common_Repos {0}
	set IP_Description {}
	set IP_Dir {}
	set IP_Library_Text {mkidgen3}
	set IP_LifeCycle_Menu {2}
	set IP_Logo {sysgen_icon_100.png}
	set IP_Name {ssrfft_16x4096_axis_growth}
	set IP_Revision {280672547}
	set IP_Socket_IP {0}
	set IP_Socket_IP_Proj_Path {}
	set IP_Vendor_Text {MazinLab}
	set IP_Version_Text {1.4}
	set ImplStrategyName {Vivado Implementation Defaults}
	set PostProjectCreationProc {dsp_package_for_vivado_ip_integrator}
	set Project {ssrfft_16x4096_axis_growth}
	set ProjectFiles {
		{{conv_pkg.v}}
		{{synth_reg.v}}
		{{synth_reg_w_init.v}}
		{{convert_type.v}}
		{{xlclockdriver_rd.v}}
		{{COMPLEX_FIXED_PKG.vhd}}
		{{BDELAY.vhd}}
		{{UDELAY.vhd}}
		{{SDELAY.vhd}}
		{{CDELAY.vhd}}
		{{CB.vhd}}
		{{BFS.vhd}}
		{{CBFS.vhd}}
		{{CSA3.vhd}}
		{{DSP48E2GW.vhd}}
		{{CKCM.vhd}}
		{{ADDSUB.vhd}}
		{{TABLE.vhd}}
		{{CM3.vhd}}
		{{CM3FFT.vhd}}
		{{PARFFT.vhd}}
		{{INPUT_SWAP.vhd}}
		{{SYSTOLIC_FFT.vhd}}
		{{DS.vhd}}
		{{DSN.vhd}}
		{{VECTOR_FFT.vhd}}
		{{WRAPPER_VECTOR_FFT.vhd}}
		{{ssrfft_16x4096_axis_growth_entity_declarations.v}}
		{{ssrfft_16x4096_axis_growth.v}}
		{{ssrfft_16x4096_axis_growth_clock.xdc}}
		{{ssrfft_16x4096_axis_growth.xdc}}
	}
	set SimPeriod 1
	set SimTime 10
	set SimulationTime {219.99999991 ns}
	set SynthStrategyName {Vivado Synthesis Defaults}
	set SynthesisTool {Vivado}
	set TargetDir {/home/jpsmith/Gen3/mkidgen3/firmware/blocks/ssrfft_16x4096}
	set TopLevelModule {ssrfft_16x4096_axis_growth}
	set TopLevelSimulinkHandle 0.00012207
	set TopLevelPortInterface {}
	dict set TopLevelPortInterface iq_tvalid_15 Name {iq_tvalid_15}
	dict set TopLevelPortInterface iq_tvalid_15 Type Bool
	dict set TopLevelPortInterface iq_tvalid_15 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_15 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_15 Width 1
	dict set TopLevelPortInterface iq_tvalid_15 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_15.dat}
	dict set TopLevelPortInterface iq_tvalid_15 IconText {iq_tvalid_15}
	dict set TopLevelPortInterface iq_tvalid_15 Direction in
	dict set TopLevelPortInterface iq_tvalid_15 Period 1
	dict set TopLevelPortInterface iq_tvalid_15 Interface 0
	dict set TopLevelPortInterface iq_tvalid_15 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_15 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_15 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_15 Locs {}
	dict set TopLevelPortInterface iq_tvalid_15 IOStandard {}
	dict set TopLevelPortInterface iq_tvalid_14 Name {iq_tvalid_14}
	dict set TopLevelPortInterface iq_tvalid_14 Type Bool
	dict set TopLevelPortInterface iq_tvalid_14 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_14 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_14 Width 1
	dict set TopLevelPortInterface iq_tvalid_14 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_14.dat}
	dict set TopLevelPortInterface iq_tvalid_14 IconText {iq_tvalid_14}
	dict set TopLevelPortInterface iq_tvalid_14 Direction in
	dict set TopLevelPortInterface iq_tvalid_14 Period 1
	dict set TopLevelPortInterface iq_tvalid_14 Interface 0
	dict set TopLevelPortInterface iq_tvalid_14 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_14 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_14 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_14 Locs {}
	dict set TopLevelPortInterface iq_tvalid_14 IOStandard {}
	dict set TopLevelPortInterface iq_tvalid_13 Name {iq_tvalid_13}
	dict set TopLevelPortInterface iq_tvalid_13 Type Bool
	dict set TopLevelPortInterface iq_tvalid_13 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_13 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_13 Width 1
	dict set TopLevelPortInterface iq_tvalid_13 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_13.dat}
	dict set TopLevelPortInterface iq_tvalid_13 IconText {iq_tvalid_13}
	dict set TopLevelPortInterface iq_tvalid_13 Direction in
	dict set TopLevelPortInterface iq_tvalid_13 Period 1
	dict set TopLevelPortInterface iq_tvalid_13 Interface 0
	dict set TopLevelPortInterface iq_tvalid_13 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_13 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_13 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_13 Locs {}
	dict set TopLevelPortInterface iq_tvalid_13 IOStandard {}
	dict set TopLevelPortInterface iq_tvalid_12 Name {iq_tvalid_12}
	dict set TopLevelPortInterface iq_tvalid_12 Type Bool
	dict set TopLevelPortInterface iq_tvalid_12 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_12 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_12 Width 1
	dict set TopLevelPortInterface iq_tvalid_12 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_12.dat}
	dict set TopLevelPortInterface iq_tvalid_12 IconText {iq_tvalid_12}
	dict set TopLevelPortInterface iq_tvalid_12 Direction in
	dict set TopLevelPortInterface iq_tvalid_12 Period 1
	dict set TopLevelPortInterface iq_tvalid_12 Interface 0
	dict set TopLevelPortInterface iq_tvalid_12 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_12 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_12 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_12 Locs {}
	dict set TopLevelPortInterface iq_tvalid_12 IOStandard {}
	dict set TopLevelPortInterface iq_tvalid_11 Name {iq_tvalid_11}
	dict set TopLevelPortInterface iq_tvalid_11 Type Bool
	dict set TopLevelPortInterface iq_tvalid_11 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_11 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_11 Width 1
	dict set TopLevelPortInterface iq_tvalid_11 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_11.dat}
	dict set TopLevelPortInterface iq_tvalid_11 IconText {iq_tvalid_11}
	dict set TopLevelPortInterface iq_tvalid_11 Direction in
	dict set TopLevelPortInterface iq_tvalid_11 Period 1
	dict set TopLevelPortInterface iq_tvalid_11 Interface 0
	dict set TopLevelPortInterface iq_tvalid_11 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_11 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_11 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_11 Locs {}
	dict set TopLevelPortInterface iq_tvalid_11 IOStandard {}
	dict set TopLevelPortInterface iq_tvalid_10 Name {iq_tvalid_10}
	dict set TopLevelPortInterface iq_tvalid_10 Type Bool
	dict set TopLevelPortInterface iq_tvalid_10 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_10 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_10 Width 1
	dict set TopLevelPortInterface iq_tvalid_10 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_10.dat}
	dict set TopLevelPortInterface iq_tvalid_10 IconText {iq_tvalid_10}
	dict set TopLevelPortInterface iq_tvalid_10 Direction in
	dict set TopLevelPortInterface iq_tvalid_10 Period 1
	dict set TopLevelPortInterface iq_tvalid_10 Interface 0
	dict set TopLevelPortInterface iq_tvalid_10 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_10 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_10 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_10 Locs {}
	dict set TopLevelPortInterface iq_tvalid_10 IOStandard {}
	dict set TopLevelPortInterface iq_tvalid_9 Name {iq_tvalid_9}
	dict set TopLevelPortInterface iq_tvalid_9 Type Bool
	dict set TopLevelPortInterface iq_tvalid_9 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_9 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_9 Width 1
	dict set TopLevelPortInterface iq_tvalid_9 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_9.dat}
	dict set TopLevelPortInterface iq_tvalid_9 IconText {iq_tvalid_9}
	dict set TopLevelPortInterface iq_tvalid_9 Direction in
	dict set TopLevelPortInterface iq_tvalid_9 Period 1
	dict set TopLevelPortInterface iq_tvalid_9 Interface 0
	dict set TopLevelPortInterface iq_tvalid_9 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_9 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_9 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_9 Locs {}
	dict set TopLevelPortInterface iq_tvalid_9 IOStandard {}
	dict set TopLevelPortInterface iq_tvalid_8 Name {iq_tvalid_8}
	dict set TopLevelPortInterface iq_tvalid_8 Type Bool
	dict set TopLevelPortInterface iq_tvalid_8 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_8 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_8 Width 1
	dict set TopLevelPortInterface iq_tvalid_8 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_8.dat}
	dict set TopLevelPortInterface iq_tvalid_8 IconText {iq_tvalid_8}
	dict set TopLevelPortInterface iq_tvalid_8 Direction in
	dict set TopLevelPortInterface iq_tvalid_8 Period 1
	dict set TopLevelPortInterface iq_tvalid_8 Interface 0
	dict set TopLevelPortInterface iq_tvalid_8 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_8 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_8 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_8 Locs {}
	dict set TopLevelPortInterface iq_tvalid_8 IOStandard {}
	dict set TopLevelPortInterface iq_tvalid_7 Name {iq_tvalid_7}
	dict set TopLevelPortInterface iq_tvalid_7 Type Bool
	dict set TopLevelPortInterface iq_tvalid_7 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_7 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_7 Width 1
	dict set TopLevelPortInterface iq_tvalid_7 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_7.dat}
	dict set TopLevelPortInterface iq_tvalid_7 IconText {iq_tvalid_7}
	dict set TopLevelPortInterface iq_tvalid_7 Direction in
	dict set TopLevelPortInterface iq_tvalid_7 Period 1
	dict set TopLevelPortInterface iq_tvalid_7 Interface 0
	dict set TopLevelPortInterface iq_tvalid_7 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_7 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_7 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_7 Locs {}
	dict set TopLevelPortInterface iq_tvalid_7 IOStandard {}
	dict set TopLevelPortInterface iq_tvalid_6 Name {iq_tvalid_6}
	dict set TopLevelPortInterface iq_tvalid_6 Type Bool
	dict set TopLevelPortInterface iq_tvalid_6 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_6 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_6 Width 1
	dict set TopLevelPortInterface iq_tvalid_6 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_6.dat}
	dict set TopLevelPortInterface iq_tvalid_6 IconText {iq_tvalid_6}
	dict set TopLevelPortInterface iq_tvalid_6 Direction in
	dict set TopLevelPortInterface iq_tvalid_6 Period 1
	dict set TopLevelPortInterface iq_tvalid_6 Interface 0
	dict set TopLevelPortInterface iq_tvalid_6 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_6 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_6 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_6 Locs {}
	dict set TopLevelPortInterface iq_tvalid_6 IOStandard {}
	dict set TopLevelPortInterface iq_tvalid_5 Name {iq_tvalid_5}
	dict set TopLevelPortInterface iq_tvalid_5 Type Bool
	dict set TopLevelPortInterface iq_tvalid_5 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_5 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_5 Width 1
	dict set TopLevelPortInterface iq_tvalid_5 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_5.dat}
	dict set TopLevelPortInterface iq_tvalid_5 IconText {iq_tvalid_5}
	dict set TopLevelPortInterface iq_tvalid_5 Direction in
	dict set TopLevelPortInterface iq_tvalid_5 Period 1
	dict set TopLevelPortInterface iq_tvalid_5 Interface 0
	dict set TopLevelPortInterface iq_tvalid_5 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_5 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_5 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_5 Locs {}
	dict set TopLevelPortInterface iq_tvalid_5 IOStandard {}
	dict set TopLevelPortInterface iq_tvalid_4 Name {iq_tvalid_4}
	dict set TopLevelPortInterface iq_tvalid_4 Type Bool
	dict set TopLevelPortInterface iq_tvalid_4 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_4 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_4 Width 1
	dict set TopLevelPortInterface iq_tvalid_4 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_4.dat}
	dict set TopLevelPortInterface iq_tvalid_4 IconText {iq_tvalid_4}
	dict set TopLevelPortInterface iq_tvalid_4 Direction in
	dict set TopLevelPortInterface iq_tvalid_4 Period 1
	dict set TopLevelPortInterface iq_tvalid_4 Interface 0
	dict set TopLevelPortInterface iq_tvalid_4 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_4 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_4 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_4 Locs {}
	dict set TopLevelPortInterface iq_tvalid_4 IOStandard {}
	dict set TopLevelPortInterface iq_tvalid_3 Name {iq_tvalid_3}
	dict set TopLevelPortInterface iq_tvalid_3 Type Bool
	dict set TopLevelPortInterface iq_tvalid_3 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_3 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_3 Width 1
	dict set TopLevelPortInterface iq_tvalid_3 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_3.dat}
	dict set TopLevelPortInterface iq_tvalid_3 IconText {iq_tvalid_3}
	dict set TopLevelPortInterface iq_tvalid_3 Direction in
	dict set TopLevelPortInterface iq_tvalid_3 Period 1
	dict set TopLevelPortInterface iq_tvalid_3 Interface 0
	dict set TopLevelPortInterface iq_tvalid_3 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_3 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_3 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_3 Locs {}
	dict set TopLevelPortInterface iq_tvalid_3 IOStandard {}
	dict set TopLevelPortInterface iq_tvalid_2 Name {iq_tvalid_2}
	dict set TopLevelPortInterface iq_tvalid_2 Type Bool
	dict set TopLevelPortInterface iq_tvalid_2 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_2 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_2 Width 1
	dict set TopLevelPortInterface iq_tvalid_2 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_2.dat}
	dict set TopLevelPortInterface iq_tvalid_2 IconText {iq_tvalid_2}
	dict set TopLevelPortInterface iq_tvalid_2 Direction in
	dict set TopLevelPortInterface iq_tvalid_2 Period 1
	dict set TopLevelPortInterface iq_tvalid_2 Interface 0
	dict set TopLevelPortInterface iq_tvalid_2 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_2 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_2 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_2 Locs {}
	dict set TopLevelPortInterface iq_tvalid_2 IOStandard {}
	dict set TopLevelPortInterface iq_tvalid_1 Name {iq_tvalid_1}
	dict set TopLevelPortInterface iq_tvalid_1 Type Bool
	dict set TopLevelPortInterface iq_tvalid_1 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_1 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_1 Width 1
	dict set TopLevelPortInterface iq_tvalid_1 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_1.dat}
	dict set TopLevelPortInterface iq_tvalid_1 IconText {iq_tvalid_1}
	dict set TopLevelPortInterface iq_tvalid_1 Direction in
	dict set TopLevelPortInterface iq_tvalid_1 Period 1
	dict set TopLevelPortInterface iq_tvalid_1 Interface 0
	dict set TopLevelPortInterface iq_tvalid_1 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_1 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_1 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_1 Locs {}
	dict set TopLevelPortInterface iq_tvalid_1 IOStandard {}
	dict set TopLevelPortInterface iq_tvalid_0 Name {iq_tvalid_0}
	dict set TopLevelPortInterface iq_tvalid_0 Type Bool
	dict set TopLevelPortInterface iq_tvalid_0 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tvalid_0 BinaryPoint 0
	dict set TopLevelPortInterface iq_tvalid_0 Width 1
	dict set TopLevelPortInterface iq_tvalid_0 DatFile {ssrfft_16x4096_axis_growth_iq_tvalid_iq_tvalid_0.dat}
	dict set TopLevelPortInterface iq_tvalid_0 IconText {iq_tvalid_0}
	dict set TopLevelPortInterface iq_tvalid_0 Direction in
	dict set TopLevelPortInterface iq_tvalid_0 Period 1
	dict set TopLevelPortInterface iq_tvalid_0 Interface 0
	dict set TopLevelPortInterface iq_tvalid_0 InterfaceName {}
	dict set TopLevelPortInterface iq_tvalid_0 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tvalid_0 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tvalid_0 Locs {}
	dict set TopLevelPortInterface iq_tvalid_0 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_15 Name {iq_tdata_15}
	dict set TopLevelPortInterface iq_tdata_15 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_15 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_15 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_15 Width 32
	dict set TopLevelPortInterface iq_tdata_15 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_15.dat}
	dict set TopLevelPortInterface iq_tdata_15 IconText {iq_tdata_15}
	dict set TopLevelPortInterface iq_tdata_15 Direction in
	dict set TopLevelPortInterface iq_tdata_15 Period 1
	dict set TopLevelPortInterface iq_tdata_15 Interface 0
	dict set TopLevelPortInterface iq_tdata_15 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_15 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_15 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_15 Locs {}
	dict set TopLevelPortInterface iq_tdata_15 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_14 Name {iq_tdata_14}
	dict set TopLevelPortInterface iq_tdata_14 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_14 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_14 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_14 Width 32
	dict set TopLevelPortInterface iq_tdata_14 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_14.dat}
	dict set TopLevelPortInterface iq_tdata_14 IconText {iq_tdata_14}
	dict set TopLevelPortInterface iq_tdata_14 Direction in
	dict set TopLevelPortInterface iq_tdata_14 Period 1
	dict set TopLevelPortInterface iq_tdata_14 Interface 0
	dict set TopLevelPortInterface iq_tdata_14 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_14 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_14 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_14 Locs {}
	dict set TopLevelPortInterface iq_tdata_14 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_13 Name {iq_tdata_13}
	dict set TopLevelPortInterface iq_tdata_13 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_13 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_13 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_13 Width 32
	dict set TopLevelPortInterface iq_tdata_13 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_13.dat}
	dict set TopLevelPortInterface iq_tdata_13 IconText {iq_tdata_13}
	dict set TopLevelPortInterface iq_tdata_13 Direction in
	dict set TopLevelPortInterface iq_tdata_13 Period 1
	dict set TopLevelPortInterface iq_tdata_13 Interface 0
	dict set TopLevelPortInterface iq_tdata_13 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_13 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_13 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_13 Locs {}
	dict set TopLevelPortInterface iq_tdata_13 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_12 Name {iq_tdata_12}
	dict set TopLevelPortInterface iq_tdata_12 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_12 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_12 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_12 Width 32
	dict set TopLevelPortInterface iq_tdata_12 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_12.dat}
	dict set TopLevelPortInterface iq_tdata_12 IconText {iq_tdata_12}
	dict set TopLevelPortInterface iq_tdata_12 Direction in
	dict set TopLevelPortInterface iq_tdata_12 Period 1
	dict set TopLevelPortInterface iq_tdata_12 Interface 0
	dict set TopLevelPortInterface iq_tdata_12 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_12 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_12 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_12 Locs {}
	dict set TopLevelPortInterface iq_tdata_12 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_11 Name {iq_tdata_11}
	dict set TopLevelPortInterface iq_tdata_11 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_11 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_11 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_11 Width 32
	dict set TopLevelPortInterface iq_tdata_11 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_11.dat}
	dict set TopLevelPortInterface iq_tdata_11 IconText {iq_tdata_11}
	dict set TopLevelPortInterface iq_tdata_11 Direction in
	dict set TopLevelPortInterface iq_tdata_11 Period 1
	dict set TopLevelPortInterface iq_tdata_11 Interface 0
	dict set TopLevelPortInterface iq_tdata_11 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_11 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_11 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_11 Locs {}
	dict set TopLevelPortInterface iq_tdata_11 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_10 Name {iq_tdata_10}
	dict set TopLevelPortInterface iq_tdata_10 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_10 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_10 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_10 Width 32
	dict set TopLevelPortInterface iq_tdata_10 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_10.dat}
	dict set TopLevelPortInterface iq_tdata_10 IconText {iq_tdata_10}
	dict set TopLevelPortInterface iq_tdata_10 Direction in
	dict set TopLevelPortInterface iq_tdata_10 Period 1
	dict set TopLevelPortInterface iq_tdata_10 Interface 0
	dict set TopLevelPortInterface iq_tdata_10 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_10 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_10 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_10 Locs {}
	dict set TopLevelPortInterface iq_tdata_10 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_9 Name {iq_tdata_9}
	dict set TopLevelPortInterface iq_tdata_9 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_9 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_9 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_9 Width 32
	dict set TopLevelPortInterface iq_tdata_9 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_9.dat}
	dict set TopLevelPortInterface iq_tdata_9 IconText {iq_tdata_9}
	dict set TopLevelPortInterface iq_tdata_9 Direction in
	dict set TopLevelPortInterface iq_tdata_9 Period 1
	dict set TopLevelPortInterface iq_tdata_9 Interface 0
	dict set TopLevelPortInterface iq_tdata_9 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_9 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_9 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_9 Locs {}
	dict set TopLevelPortInterface iq_tdata_9 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_8 Name {iq_tdata_8}
	dict set TopLevelPortInterface iq_tdata_8 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_8 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_8 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_8 Width 32
	dict set TopLevelPortInterface iq_tdata_8 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_8.dat}
	dict set TopLevelPortInterface iq_tdata_8 IconText {iq_tdata_8}
	dict set TopLevelPortInterface iq_tdata_8 Direction in
	dict set TopLevelPortInterface iq_tdata_8 Period 1
	dict set TopLevelPortInterface iq_tdata_8 Interface 0
	dict set TopLevelPortInterface iq_tdata_8 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_8 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_8 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_8 Locs {}
	dict set TopLevelPortInterface iq_tdata_8 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_7 Name {iq_tdata_7}
	dict set TopLevelPortInterface iq_tdata_7 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_7 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_7 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_7 Width 32
	dict set TopLevelPortInterface iq_tdata_7 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_7.dat}
	dict set TopLevelPortInterface iq_tdata_7 IconText {iq_tdata_7}
	dict set TopLevelPortInterface iq_tdata_7 Direction in
	dict set TopLevelPortInterface iq_tdata_7 Period 1
	dict set TopLevelPortInterface iq_tdata_7 Interface 0
	dict set TopLevelPortInterface iq_tdata_7 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_7 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_7 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_7 Locs {}
	dict set TopLevelPortInterface iq_tdata_7 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_6 Name {iq_tdata_6}
	dict set TopLevelPortInterface iq_tdata_6 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_6 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_6 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_6 Width 32
	dict set TopLevelPortInterface iq_tdata_6 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_6.dat}
	dict set TopLevelPortInterface iq_tdata_6 IconText {iq_tdata_6}
	dict set TopLevelPortInterface iq_tdata_6 Direction in
	dict set TopLevelPortInterface iq_tdata_6 Period 1
	dict set TopLevelPortInterface iq_tdata_6 Interface 0
	dict set TopLevelPortInterface iq_tdata_6 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_6 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_6 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_6 Locs {}
	dict set TopLevelPortInterface iq_tdata_6 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_5 Name {iq_tdata_5}
	dict set TopLevelPortInterface iq_tdata_5 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_5 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_5 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_5 Width 32
	dict set TopLevelPortInterface iq_tdata_5 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_5.dat}
	dict set TopLevelPortInterface iq_tdata_5 IconText {iq_tdata_5}
	dict set TopLevelPortInterface iq_tdata_5 Direction in
	dict set TopLevelPortInterface iq_tdata_5 Period 1
	dict set TopLevelPortInterface iq_tdata_5 Interface 0
	dict set TopLevelPortInterface iq_tdata_5 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_5 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_5 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_5 Locs {}
	dict set TopLevelPortInterface iq_tdata_5 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_4 Name {iq_tdata_4}
	dict set TopLevelPortInterface iq_tdata_4 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_4 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_4 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_4 Width 32
	dict set TopLevelPortInterface iq_tdata_4 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_4.dat}
	dict set TopLevelPortInterface iq_tdata_4 IconText {iq_tdata_4}
	dict set TopLevelPortInterface iq_tdata_4 Direction in
	dict set TopLevelPortInterface iq_tdata_4 Period 1
	dict set TopLevelPortInterface iq_tdata_4 Interface 0
	dict set TopLevelPortInterface iq_tdata_4 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_4 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_4 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_4 Locs {}
	dict set TopLevelPortInterface iq_tdata_4 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_3 Name {iq_tdata_3}
	dict set TopLevelPortInterface iq_tdata_3 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_3 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_3 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_3 Width 32
	dict set TopLevelPortInterface iq_tdata_3 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_3.dat}
	dict set TopLevelPortInterface iq_tdata_3 IconText {iq_tdata_3}
	dict set TopLevelPortInterface iq_tdata_3 Direction in
	dict set TopLevelPortInterface iq_tdata_3 Period 1
	dict set TopLevelPortInterface iq_tdata_3 Interface 0
	dict set TopLevelPortInterface iq_tdata_3 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_3 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_3 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_3 Locs {}
	dict set TopLevelPortInterface iq_tdata_3 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_2 Name {iq_tdata_2}
	dict set TopLevelPortInterface iq_tdata_2 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_2 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_2 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_2 Width 32
	dict set TopLevelPortInterface iq_tdata_2 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_2.dat}
	dict set TopLevelPortInterface iq_tdata_2 IconText {iq_tdata_2}
	dict set TopLevelPortInterface iq_tdata_2 Direction in
	dict set TopLevelPortInterface iq_tdata_2 Period 1
	dict set TopLevelPortInterface iq_tdata_2 Interface 0
	dict set TopLevelPortInterface iq_tdata_2 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_2 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_2 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_2 Locs {}
	dict set TopLevelPortInterface iq_tdata_2 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_1 Name {iq_tdata_1}
	dict set TopLevelPortInterface iq_tdata_1 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_1 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_1 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_1 Width 32
	dict set TopLevelPortInterface iq_tdata_1 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_1.dat}
	dict set TopLevelPortInterface iq_tdata_1 IconText {iq_tdata_1}
	dict set TopLevelPortInterface iq_tdata_1 Direction in
	dict set TopLevelPortInterface iq_tdata_1 Period 1
	dict set TopLevelPortInterface iq_tdata_1 Interface 0
	dict set TopLevelPortInterface iq_tdata_1 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_1 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_1 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_1 Locs {}
	dict set TopLevelPortInterface iq_tdata_1 IOStandard {}
	dict set TopLevelPortInterface iq_tdata_0 Name {iq_tdata_0}
	dict set TopLevelPortInterface iq_tdata_0 Type UFix_32_0
	dict set TopLevelPortInterface iq_tdata_0 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tdata_0 BinaryPoint 0
	dict set TopLevelPortInterface iq_tdata_0 Width 32
	dict set TopLevelPortInterface iq_tdata_0 DatFile {ssrfft_16x4096_axis_growth_iq_tdata_iq_tdata_0.dat}
	dict set TopLevelPortInterface iq_tdata_0 IconText {iq_tdata_0}
	dict set TopLevelPortInterface iq_tdata_0 Direction in
	dict set TopLevelPortInterface iq_tdata_0 Period 1
	dict set TopLevelPortInterface iq_tdata_0 Interface 0
	dict set TopLevelPortInterface iq_tdata_0 InterfaceName {}
	dict set TopLevelPortInterface iq_tdata_0 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tdata_0 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tdata_0 Locs {}
	dict set TopLevelPortInterface iq_tdata_0 IOStandard {}
	dict set TopLevelPortInterface scale_in Name {scale_in}
	dict set TopLevelPortInterface scale_in Type UFix_12_0
	dict set TopLevelPortInterface scale_in ArithmeticType xlUnsigned
	dict set TopLevelPortInterface scale_in BinaryPoint 0
	dict set TopLevelPortInterface scale_in Width 12
	dict set TopLevelPortInterface scale_in DatFile {ssrfft_16x4096_axis_growth_scale_in.dat}
	dict set TopLevelPortInterface scale_in IconText {scale_in}
	dict set TopLevelPortInterface scale_in Direction in
	dict set TopLevelPortInterface scale_in Period 1
	dict set TopLevelPortInterface scale_in Interface 0
	dict set TopLevelPortInterface scale_in InterfaceName {}
	dict set TopLevelPortInterface scale_in InterfaceString {DATA}
	dict set TopLevelPortInterface scale_in ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface scale_in Locs {}
	dict set TopLevelPortInterface scale_in IOStandard {}
	dict set TopLevelPortInterface biniq_valid Name {biniq_valid}
	dict set TopLevelPortInterface biniq_valid Type Bool
	dict set TopLevelPortInterface biniq_valid ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_valid BinaryPoint 0
	dict set TopLevelPortInterface biniq_valid Width 1
	dict set TopLevelPortInterface biniq_valid DatFile {ssrfft_16x4096_axis_growth_biniq_valid.dat}
	dict set TopLevelPortInterface biniq_valid IconText {biniq_valid
}
	dict set TopLevelPortInterface biniq_valid Direction out
	dict set TopLevelPortInterface biniq_valid Period 1
	dict set TopLevelPortInterface biniq_valid Interface 0
	dict set TopLevelPortInterface biniq_valid InterfaceName {}
	dict set TopLevelPortInterface biniq_valid InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_valid ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_valid Locs {}
	dict set TopLevelPortInterface biniq_valid IOStandard {}
	dict set TopLevelPortInterface scale_out Name {scale_out}
	dict set TopLevelPortInterface scale_out Type UFix_12_0
	dict set TopLevelPortInterface scale_out ArithmeticType xlUnsigned
	dict set TopLevelPortInterface scale_out BinaryPoint 0
	dict set TopLevelPortInterface scale_out Width 12
	dict set TopLevelPortInterface scale_out DatFile {ssrfft_16x4096_axis_growth_scale_out.dat}
	dict set TopLevelPortInterface scale_out IconText {scale_out}
	dict set TopLevelPortInterface scale_out Direction out
	dict set TopLevelPortInterface scale_out Period 1
	dict set TopLevelPortInterface scale_out Interface 0
	dict set TopLevelPortInterface scale_out InterfaceName {}
	dict set TopLevelPortInterface scale_out InterfaceString {DATA}
	dict set TopLevelPortInterface scale_out ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface scale_out Locs {}
	dict set TopLevelPortInterface scale_out IOStandard {}
	dict set TopLevelPortInterface biniq_0 Name {biniq_0}
	dict set TopLevelPortInterface biniq_0 Type UFix_32_0
	dict set TopLevelPortInterface biniq_0 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_0 BinaryPoint 0
	dict set TopLevelPortInterface biniq_0 Width 32
	dict set TopLevelPortInterface biniq_0 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_0.dat}
	dict set TopLevelPortInterface biniq_0 IconText {biniq_0}
	dict set TopLevelPortInterface biniq_0 Direction out
	dict set TopLevelPortInterface biniq_0 Period 1
	dict set TopLevelPortInterface biniq_0 Interface 0
	dict set TopLevelPortInterface biniq_0 InterfaceName {}
	dict set TopLevelPortInterface biniq_0 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_0 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_0 Locs {}
	dict set TopLevelPortInterface biniq_0 IOStandard {}
	dict set TopLevelPortInterface biniq_1 Name {biniq_1}
	dict set TopLevelPortInterface biniq_1 Type UFix_32_0
	dict set TopLevelPortInterface biniq_1 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_1 BinaryPoint 0
	dict set TopLevelPortInterface biniq_1 Width 32
	dict set TopLevelPortInterface biniq_1 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_1.dat}
	dict set TopLevelPortInterface biniq_1 IconText {biniq_1}
	dict set TopLevelPortInterface biniq_1 Direction out
	dict set TopLevelPortInterface biniq_1 Period 1
	dict set TopLevelPortInterface biniq_1 Interface 0
	dict set TopLevelPortInterface biniq_1 InterfaceName {}
	dict set TopLevelPortInterface biniq_1 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_1 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_1 Locs {}
	dict set TopLevelPortInterface biniq_1 IOStandard {}
	dict set TopLevelPortInterface biniq_2 Name {biniq_2}
	dict set TopLevelPortInterface biniq_2 Type UFix_32_0
	dict set TopLevelPortInterface biniq_2 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_2 BinaryPoint 0
	dict set TopLevelPortInterface biniq_2 Width 32
	dict set TopLevelPortInterface biniq_2 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_2.dat}
	dict set TopLevelPortInterface biniq_2 IconText {biniq_2}
	dict set TopLevelPortInterface biniq_2 Direction out
	dict set TopLevelPortInterface biniq_2 Period 1
	dict set TopLevelPortInterface biniq_2 Interface 0
	dict set TopLevelPortInterface biniq_2 InterfaceName {}
	dict set TopLevelPortInterface biniq_2 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_2 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_2 Locs {}
	dict set TopLevelPortInterface biniq_2 IOStandard {}
	dict set TopLevelPortInterface biniq_3 Name {biniq_3}
	dict set TopLevelPortInterface biniq_3 Type UFix_32_0
	dict set TopLevelPortInterface biniq_3 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_3 BinaryPoint 0
	dict set TopLevelPortInterface biniq_3 Width 32
	dict set TopLevelPortInterface biniq_3 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_3.dat}
	dict set TopLevelPortInterface biniq_3 IconText {biniq_3}
	dict set TopLevelPortInterface biniq_3 Direction out
	dict set TopLevelPortInterface biniq_3 Period 1
	dict set TopLevelPortInterface biniq_3 Interface 0
	dict set TopLevelPortInterface biniq_3 InterfaceName {}
	dict set TopLevelPortInterface biniq_3 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_3 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_3 Locs {}
	dict set TopLevelPortInterface biniq_3 IOStandard {}
	dict set TopLevelPortInterface biniq_4 Name {biniq_4}
	dict set TopLevelPortInterface biniq_4 Type UFix_32_0
	dict set TopLevelPortInterface biniq_4 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_4 BinaryPoint 0
	dict set TopLevelPortInterface biniq_4 Width 32
	dict set TopLevelPortInterface biniq_4 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_4.dat}
	dict set TopLevelPortInterface biniq_4 IconText {biniq_4}
	dict set TopLevelPortInterface biniq_4 Direction out
	dict set TopLevelPortInterface biniq_4 Period 1
	dict set TopLevelPortInterface biniq_4 Interface 0
	dict set TopLevelPortInterface biniq_4 InterfaceName {}
	dict set TopLevelPortInterface biniq_4 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_4 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_4 Locs {}
	dict set TopLevelPortInterface biniq_4 IOStandard {}
	dict set TopLevelPortInterface biniq_5 Name {biniq_5}
	dict set TopLevelPortInterface biniq_5 Type UFix_32_0
	dict set TopLevelPortInterface biniq_5 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_5 BinaryPoint 0
	dict set TopLevelPortInterface biniq_5 Width 32
	dict set TopLevelPortInterface biniq_5 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_5.dat}
	dict set TopLevelPortInterface biniq_5 IconText {biniq_5}
	dict set TopLevelPortInterface biniq_5 Direction out
	dict set TopLevelPortInterface biniq_5 Period 1
	dict set TopLevelPortInterface biniq_5 Interface 0
	dict set TopLevelPortInterface biniq_5 InterfaceName {}
	dict set TopLevelPortInterface biniq_5 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_5 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_5 Locs {}
	dict set TopLevelPortInterface biniq_5 IOStandard {}
	dict set TopLevelPortInterface biniq_6 Name {biniq_6}
	dict set TopLevelPortInterface biniq_6 Type UFix_32_0
	dict set TopLevelPortInterface biniq_6 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_6 BinaryPoint 0
	dict set TopLevelPortInterface biniq_6 Width 32
	dict set TopLevelPortInterface biniq_6 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_6.dat}
	dict set TopLevelPortInterface biniq_6 IconText {biniq_6}
	dict set TopLevelPortInterface biniq_6 Direction out
	dict set TopLevelPortInterface biniq_6 Period 1
	dict set TopLevelPortInterface biniq_6 Interface 0
	dict set TopLevelPortInterface biniq_6 InterfaceName {}
	dict set TopLevelPortInterface biniq_6 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_6 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_6 Locs {}
	dict set TopLevelPortInterface biniq_6 IOStandard {}
	dict set TopLevelPortInterface biniq_7 Name {biniq_7}
	dict set TopLevelPortInterface biniq_7 Type UFix_32_0
	dict set TopLevelPortInterface biniq_7 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_7 BinaryPoint 0
	dict set TopLevelPortInterface biniq_7 Width 32
	dict set TopLevelPortInterface biniq_7 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_7.dat}
	dict set TopLevelPortInterface biniq_7 IconText {biniq_7}
	dict set TopLevelPortInterface biniq_7 Direction out
	dict set TopLevelPortInterface biniq_7 Period 1
	dict set TopLevelPortInterface biniq_7 Interface 0
	dict set TopLevelPortInterface biniq_7 InterfaceName {}
	dict set TopLevelPortInterface biniq_7 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_7 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_7 Locs {}
	dict set TopLevelPortInterface biniq_7 IOStandard {}
	dict set TopLevelPortInterface biniq_8 Name {biniq_8}
	dict set TopLevelPortInterface biniq_8 Type UFix_32_0
	dict set TopLevelPortInterface biniq_8 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_8 BinaryPoint 0
	dict set TopLevelPortInterface biniq_8 Width 32
	dict set TopLevelPortInterface biniq_8 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_8.dat}
	dict set TopLevelPortInterface biniq_8 IconText {biniq_8}
	dict set TopLevelPortInterface biniq_8 Direction out
	dict set TopLevelPortInterface biniq_8 Period 1
	dict set TopLevelPortInterface biniq_8 Interface 0
	dict set TopLevelPortInterface biniq_8 InterfaceName {}
	dict set TopLevelPortInterface biniq_8 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_8 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_8 Locs {}
	dict set TopLevelPortInterface biniq_8 IOStandard {}
	dict set TopLevelPortInterface biniq_9 Name {biniq_9}
	dict set TopLevelPortInterface biniq_9 Type UFix_32_0
	dict set TopLevelPortInterface biniq_9 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_9 BinaryPoint 0
	dict set TopLevelPortInterface biniq_9 Width 32
	dict set TopLevelPortInterface biniq_9 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_9.dat}
	dict set TopLevelPortInterface biniq_9 IconText {biniq_9}
	dict set TopLevelPortInterface biniq_9 Direction out
	dict set TopLevelPortInterface biniq_9 Period 1
	dict set TopLevelPortInterface biniq_9 Interface 0
	dict set TopLevelPortInterface biniq_9 InterfaceName {}
	dict set TopLevelPortInterface biniq_9 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_9 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_9 Locs {}
	dict set TopLevelPortInterface biniq_9 IOStandard {}
	dict set TopLevelPortInterface biniq_10 Name {biniq_10}
	dict set TopLevelPortInterface biniq_10 Type UFix_32_0
	dict set TopLevelPortInterface biniq_10 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_10 BinaryPoint 0
	dict set TopLevelPortInterface biniq_10 Width 32
	dict set TopLevelPortInterface biniq_10 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_10.dat}
	dict set TopLevelPortInterface biniq_10 IconText {biniq_10}
	dict set TopLevelPortInterface biniq_10 Direction out
	dict set TopLevelPortInterface biniq_10 Period 1
	dict set TopLevelPortInterface biniq_10 Interface 0
	dict set TopLevelPortInterface biniq_10 InterfaceName {}
	dict set TopLevelPortInterface biniq_10 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_10 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_10 Locs {}
	dict set TopLevelPortInterface biniq_10 IOStandard {}
	dict set TopLevelPortInterface biniq_11 Name {biniq_11}
	dict set TopLevelPortInterface biniq_11 Type UFix_32_0
	dict set TopLevelPortInterface biniq_11 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_11 BinaryPoint 0
	dict set TopLevelPortInterface biniq_11 Width 32
	dict set TopLevelPortInterface biniq_11 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_11.dat}
	dict set TopLevelPortInterface biniq_11 IconText {biniq_11}
	dict set TopLevelPortInterface biniq_11 Direction out
	dict set TopLevelPortInterface biniq_11 Period 1
	dict set TopLevelPortInterface biniq_11 Interface 0
	dict set TopLevelPortInterface biniq_11 InterfaceName {}
	dict set TopLevelPortInterface biniq_11 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_11 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_11 Locs {}
	dict set TopLevelPortInterface biniq_11 IOStandard {}
	dict set TopLevelPortInterface biniq_12 Name {biniq_12}
	dict set TopLevelPortInterface biniq_12 Type UFix_32_0
	dict set TopLevelPortInterface biniq_12 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_12 BinaryPoint 0
	dict set TopLevelPortInterface biniq_12 Width 32
	dict set TopLevelPortInterface biniq_12 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_12.dat}
	dict set TopLevelPortInterface biniq_12 IconText {biniq_12}
	dict set TopLevelPortInterface biniq_12 Direction out
	dict set TopLevelPortInterface biniq_12 Period 1
	dict set TopLevelPortInterface biniq_12 Interface 0
	dict set TopLevelPortInterface biniq_12 InterfaceName {}
	dict set TopLevelPortInterface biniq_12 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_12 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_12 Locs {}
	dict set TopLevelPortInterface biniq_12 IOStandard {}
	dict set TopLevelPortInterface biniq_13 Name {biniq_13}
	dict set TopLevelPortInterface biniq_13 Type UFix_32_0
	dict set TopLevelPortInterface biniq_13 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_13 BinaryPoint 0
	dict set TopLevelPortInterface biniq_13 Width 32
	dict set TopLevelPortInterface biniq_13 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_13.dat}
	dict set TopLevelPortInterface biniq_13 IconText {biniq_13}
	dict set TopLevelPortInterface biniq_13 Direction out
	dict set TopLevelPortInterface biniq_13 Period 1
	dict set TopLevelPortInterface biniq_13 Interface 0
	dict set TopLevelPortInterface biniq_13 InterfaceName {}
	dict set TopLevelPortInterface biniq_13 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_13 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_13 Locs {}
	dict set TopLevelPortInterface biniq_13 IOStandard {}
	dict set TopLevelPortInterface biniq_14 Name {biniq_14}
	dict set TopLevelPortInterface biniq_14 Type UFix_32_0
	dict set TopLevelPortInterface biniq_14 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_14 BinaryPoint 0
	dict set TopLevelPortInterface biniq_14 Width 32
	dict set TopLevelPortInterface biniq_14 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_14.dat}
	dict set TopLevelPortInterface biniq_14 IconText {biniq_14}
	dict set TopLevelPortInterface biniq_14 Direction out
	dict set TopLevelPortInterface biniq_14 Period 1
	dict set TopLevelPortInterface biniq_14 Interface 0
	dict set TopLevelPortInterface biniq_14 InterfaceName {}
	dict set TopLevelPortInterface biniq_14 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_14 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_14 Locs {}
	dict set TopLevelPortInterface biniq_14 IOStandard {}
	dict set TopLevelPortInterface biniq_15 Name {biniq_15}
	dict set TopLevelPortInterface biniq_15 Type UFix_32_0
	dict set TopLevelPortInterface biniq_15 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface biniq_15 BinaryPoint 0
	dict set TopLevelPortInterface biniq_15 Width 32
	dict set TopLevelPortInterface biniq_15 DatFile {ssrfft_16x4096_axis_growth_biniq_biniq_15.dat}
	dict set TopLevelPortInterface biniq_15 IconText {biniq_15}
	dict set TopLevelPortInterface biniq_15 Direction out
	dict set TopLevelPortInterface biniq_15 Period 1
	dict set TopLevelPortInterface biniq_15 Interface 0
	dict set TopLevelPortInterface biniq_15 InterfaceName {}
	dict set TopLevelPortInterface biniq_15 InterfaceString {DATA}
	dict set TopLevelPortInterface biniq_15 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface biniq_15 Locs {}
	dict set TopLevelPortInterface biniq_15 IOStandard {}
	dict set TopLevelPortInterface iq_tready_0 Name {iq_tready_0}
	dict set TopLevelPortInterface iq_tready_0 Type Bool
	dict set TopLevelPortInterface iq_tready_0 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_0 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_0 Width 1
	dict set TopLevelPortInterface iq_tready_0 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_0.dat}
	dict set TopLevelPortInterface iq_tready_0 IconText {iq_tready_0}
	dict set TopLevelPortInterface iq_tready_0 Direction out
	dict set TopLevelPortInterface iq_tready_0 Period -1
	dict set TopLevelPortInterface iq_tready_0 Interface 0
	dict set TopLevelPortInterface iq_tready_0 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_0 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_0 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_0 Locs {}
	dict set TopLevelPortInterface iq_tready_0 IOStandard {}
	dict set TopLevelPortInterface iq_tready_1 Name {iq_tready_1}
	dict set TopLevelPortInterface iq_tready_1 Type Bool
	dict set TopLevelPortInterface iq_tready_1 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_1 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_1 Width 1
	dict set TopLevelPortInterface iq_tready_1 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_1.dat}
	dict set TopLevelPortInterface iq_tready_1 IconText {iq_tready_1}
	dict set TopLevelPortInterface iq_tready_1 Direction out
	dict set TopLevelPortInterface iq_tready_1 Period -1
	dict set TopLevelPortInterface iq_tready_1 Interface 0
	dict set TopLevelPortInterface iq_tready_1 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_1 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_1 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_1 Locs {}
	dict set TopLevelPortInterface iq_tready_1 IOStandard {}
	dict set TopLevelPortInterface iq_tready_2 Name {iq_tready_2}
	dict set TopLevelPortInterface iq_tready_2 Type Bool
	dict set TopLevelPortInterface iq_tready_2 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_2 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_2 Width 1
	dict set TopLevelPortInterface iq_tready_2 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_2.dat}
	dict set TopLevelPortInterface iq_tready_2 IconText {iq_tready_2}
	dict set TopLevelPortInterface iq_tready_2 Direction out
	dict set TopLevelPortInterface iq_tready_2 Period -1
	dict set TopLevelPortInterface iq_tready_2 Interface 0
	dict set TopLevelPortInterface iq_tready_2 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_2 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_2 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_2 Locs {}
	dict set TopLevelPortInterface iq_tready_2 IOStandard {}
	dict set TopLevelPortInterface iq_tready_3 Name {iq_tready_3}
	dict set TopLevelPortInterface iq_tready_3 Type Bool
	dict set TopLevelPortInterface iq_tready_3 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_3 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_3 Width 1
	dict set TopLevelPortInterface iq_tready_3 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_3.dat}
	dict set TopLevelPortInterface iq_tready_3 IconText {iq_tready_3}
	dict set TopLevelPortInterface iq_tready_3 Direction out
	dict set TopLevelPortInterface iq_tready_3 Period -1
	dict set TopLevelPortInterface iq_tready_3 Interface 0
	dict set TopLevelPortInterface iq_tready_3 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_3 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_3 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_3 Locs {}
	dict set TopLevelPortInterface iq_tready_3 IOStandard {}
	dict set TopLevelPortInterface iq_tready_4 Name {iq_tready_4}
	dict set TopLevelPortInterface iq_tready_4 Type Bool
	dict set TopLevelPortInterface iq_tready_4 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_4 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_4 Width 1
	dict set TopLevelPortInterface iq_tready_4 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_4.dat}
	dict set TopLevelPortInterface iq_tready_4 IconText {iq_tready_4}
	dict set TopLevelPortInterface iq_tready_4 Direction out
	dict set TopLevelPortInterface iq_tready_4 Period -1
	dict set TopLevelPortInterface iq_tready_4 Interface 0
	dict set TopLevelPortInterface iq_tready_4 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_4 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_4 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_4 Locs {}
	dict set TopLevelPortInterface iq_tready_4 IOStandard {}
	dict set TopLevelPortInterface iq_tready_5 Name {iq_tready_5}
	dict set TopLevelPortInterface iq_tready_5 Type Bool
	dict set TopLevelPortInterface iq_tready_5 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_5 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_5 Width 1
	dict set TopLevelPortInterface iq_tready_5 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_5.dat}
	dict set TopLevelPortInterface iq_tready_5 IconText {iq_tready_5}
	dict set TopLevelPortInterface iq_tready_5 Direction out
	dict set TopLevelPortInterface iq_tready_5 Period -1
	dict set TopLevelPortInterface iq_tready_5 Interface 0
	dict set TopLevelPortInterface iq_tready_5 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_5 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_5 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_5 Locs {}
	dict set TopLevelPortInterface iq_tready_5 IOStandard {}
	dict set TopLevelPortInterface iq_tready_6 Name {iq_tready_6}
	dict set TopLevelPortInterface iq_tready_6 Type Bool
	dict set TopLevelPortInterface iq_tready_6 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_6 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_6 Width 1
	dict set TopLevelPortInterface iq_tready_6 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_6.dat}
	dict set TopLevelPortInterface iq_tready_6 IconText {iq_tready_6}
	dict set TopLevelPortInterface iq_tready_6 Direction out
	dict set TopLevelPortInterface iq_tready_6 Period -1
	dict set TopLevelPortInterface iq_tready_6 Interface 0
	dict set TopLevelPortInterface iq_tready_6 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_6 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_6 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_6 Locs {}
	dict set TopLevelPortInterface iq_tready_6 IOStandard {}
	dict set TopLevelPortInterface iq_tready_7 Name {iq_tready_7}
	dict set TopLevelPortInterface iq_tready_7 Type Bool
	dict set TopLevelPortInterface iq_tready_7 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_7 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_7 Width 1
	dict set TopLevelPortInterface iq_tready_7 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_7.dat}
	dict set TopLevelPortInterface iq_tready_7 IconText {iq_tready_7}
	dict set TopLevelPortInterface iq_tready_7 Direction out
	dict set TopLevelPortInterface iq_tready_7 Period -1
	dict set TopLevelPortInterface iq_tready_7 Interface 0
	dict set TopLevelPortInterface iq_tready_7 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_7 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_7 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_7 Locs {}
	dict set TopLevelPortInterface iq_tready_7 IOStandard {}
	dict set TopLevelPortInterface iq_tready_8 Name {iq_tready_8}
	dict set TopLevelPortInterface iq_tready_8 Type Bool
	dict set TopLevelPortInterface iq_tready_8 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_8 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_8 Width 1
	dict set TopLevelPortInterface iq_tready_8 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_8.dat}
	dict set TopLevelPortInterface iq_tready_8 IconText {iq_tready_8}
	dict set TopLevelPortInterface iq_tready_8 Direction out
	dict set TopLevelPortInterface iq_tready_8 Period -1
	dict set TopLevelPortInterface iq_tready_8 Interface 0
	dict set TopLevelPortInterface iq_tready_8 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_8 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_8 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_8 Locs {}
	dict set TopLevelPortInterface iq_tready_8 IOStandard {}
	dict set TopLevelPortInterface iq_tready_9 Name {iq_tready_9}
	dict set TopLevelPortInterface iq_tready_9 Type Bool
	dict set TopLevelPortInterface iq_tready_9 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_9 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_9 Width 1
	dict set TopLevelPortInterface iq_tready_9 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_9.dat}
	dict set TopLevelPortInterface iq_tready_9 IconText {iq_tready_9}
	dict set TopLevelPortInterface iq_tready_9 Direction out
	dict set TopLevelPortInterface iq_tready_9 Period -1
	dict set TopLevelPortInterface iq_tready_9 Interface 0
	dict set TopLevelPortInterface iq_tready_9 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_9 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_9 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_9 Locs {}
	dict set TopLevelPortInterface iq_tready_9 IOStandard {}
	dict set TopLevelPortInterface iq_tready_10 Name {iq_tready_10}
	dict set TopLevelPortInterface iq_tready_10 Type Bool
	dict set TopLevelPortInterface iq_tready_10 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_10 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_10 Width 1
	dict set TopLevelPortInterface iq_tready_10 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_10.dat}
	dict set TopLevelPortInterface iq_tready_10 IconText {iq_tready_10}
	dict set TopLevelPortInterface iq_tready_10 Direction out
	dict set TopLevelPortInterface iq_tready_10 Period -1
	dict set TopLevelPortInterface iq_tready_10 Interface 0
	dict set TopLevelPortInterface iq_tready_10 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_10 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_10 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_10 Locs {}
	dict set TopLevelPortInterface iq_tready_10 IOStandard {}
	dict set TopLevelPortInterface iq_tready_11 Name {iq_tready_11}
	dict set TopLevelPortInterface iq_tready_11 Type Bool
	dict set TopLevelPortInterface iq_tready_11 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_11 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_11 Width 1
	dict set TopLevelPortInterface iq_tready_11 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_11.dat}
	dict set TopLevelPortInterface iq_tready_11 IconText {iq_tready_11}
	dict set TopLevelPortInterface iq_tready_11 Direction out
	dict set TopLevelPortInterface iq_tready_11 Period -1
	dict set TopLevelPortInterface iq_tready_11 Interface 0
	dict set TopLevelPortInterface iq_tready_11 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_11 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_11 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_11 Locs {}
	dict set TopLevelPortInterface iq_tready_11 IOStandard {}
	dict set TopLevelPortInterface iq_tready_12 Name {iq_tready_12}
	dict set TopLevelPortInterface iq_tready_12 Type Bool
	dict set TopLevelPortInterface iq_tready_12 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_12 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_12 Width 1
	dict set TopLevelPortInterface iq_tready_12 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_12.dat}
	dict set TopLevelPortInterface iq_tready_12 IconText {iq_tready_12}
	dict set TopLevelPortInterface iq_tready_12 Direction out
	dict set TopLevelPortInterface iq_tready_12 Period -1
	dict set TopLevelPortInterface iq_tready_12 Interface 0
	dict set TopLevelPortInterface iq_tready_12 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_12 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_12 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_12 Locs {}
	dict set TopLevelPortInterface iq_tready_12 IOStandard {}
	dict set TopLevelPortInterface iq_tready_13 Name {iq_tready_13}
	dict set TopLevelPortInterface iq_tready_13 Type Bool
	dict set TopLevelPortInterface iq_tready_13 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_13 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_13 Width 1
	dict set TopLevelPortInterface iq_tready_13 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_13.dat}
	dict set TopLevelPortInterface iq_tready_13 IconText {iq_tready_13}
	dict set TopLevelPortInterface iq_tready_13 Direction out
	dict set TopLevelPortInterface iq_tready_13 Period -1
	dict set TopLevelPortInterface iq_tready_13 Interface 0
	dict set TopLevelPortInterface iq_tready_13 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_13 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_13 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_13 Locs {}
	dict set TopLevelPortInterface iq_tready_13 IOStandard {}
	dict set TopLevelPortInterface iq_tready_14 Name {iq_tready_14}
	dict set TopLevelPortInterface iq_tready_14 Type Bool
	dict set TopLevelPortInterface iq_tready_14 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_14 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_14 Width 1
	dict set TopLevelPortInterface iq_tready_14 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_14.dat}
	dict set TopLevelPortInterface iq_tready_14 IconText {iq_tready_14}
	dict set TopLevelPortInterface iq_tready_14 Direction out
	dict set TopLevelPortInterface iq_tready_14 Period -1
	dict set TopLevelPortInterface iq_tready_14 Interface 0
	dict set TopLevelPortInterface iq_tready_14 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_14 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_14 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_14 Locs {}
	dict set TopLevelPortInterface iq_tready_14 IOStandard {}
	dict set TopLevelPortInterface iq_tready_15 Name {iq_tready_15}
	dict set TopLevelPortInterface iq_tready_15 Type Bool
	dict set TopLevelPortInterface iq_tready_15 ArithmeticType xlUnsigned
	dict set TopLevelPortInterface iq_tready_15 BinaryPoint 0
	dict set TopLevelPortInterface iq_tready_15 Width 1
	dict set TopLevelPortInterface iq_tready_15 DatFile {ssrfft_16x4096_axis_growth_iq_tready_iq_tready_15.dat}
	dict set TopLevelPortInterface iq_tready_15 IconText {iq_tready_15}
	dict set TopLevelPortInterface iq_tready_15 Direction out
	dict set TopLevelPortInterface iq_tready_15 Period -1
	dict set TopLevelPortInterface iq_tready_15 Interface 0
	dict set TopLevelPortInterface iq_tready_15 InterfaceName {}
	dict set TopLevelPortInterface iq_tready_15 InterfaceString {DATA}
	dict set TopLevelPortInterface iq_tready_15 ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface iq_tready_15 Locs {}
	dict set TopLevelPortInterface iq_tready_15 IOStandard {}
	dict set TopLevelPortInterface clk Name {clk}
	dict set TopLevelPortInterface clk Type -
	dict set TopLevelPortInterface clk ArithmeticType xlUnsigned
	dict set TopLevelPortInterface clk BinaryPoint 0
	dict set TopLevelPortInterface clk Width 1
	dict set TopLevelPortInterface clk DatFile {}
	dict set TopLevelPortInterface clk Direction in
	dict set TopLevelPortInterface clk Period 1
	dict set TopLevelPortInterface clk Interface 6
	dict set TopLevelPortInterface clk InterfaceName {}
	dict set TopLevelPortInterface clk InterfaceString {CLOCK}
	dict set TopLevelPortInterface clk ClockDomain {ssrfft_16x4096_axis_growth}
	dict set TopLevelPortInterface clk Locs {}
	dict set TopLevelPortInterface clk IOStandard {}
	dict set TopLevelPortInterface clk AssociatedInterfaces {}
	dict set TopLevelPortInterface clk AssociatedResets {}
	set MemoryMappedPort {}
}

source SgPaProject.tcl
::xilinx::dsp::planaheadworker::dsp_create_project